version: '3'

services:
  web:
    restart: always
    image: djangoto
    env_file: .env
    networks:
        - djlan
    depends_on:
      - mig
      
  mig:
    build: ./app
    image: djangoto
    networks:
      - djlan 
    depends_on:
      db:
        condition: service_healthy
  
  nginx:
    restart: always
    image: nginx:1.23.1
    ports:
      - "8000:8000"
    networks:
      - djlan
    volumes:
      - ./django.conf:/etc/nginx/conf.d/default.conf
  
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s  
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - djlan

networks:
  djlan:

volumes:
  pgdata:

